use_frameworks!

platform :ios, '10.0'

target 'HDStaticPod_Example' do
  pod 'HDStaticPod', :path => '../'

  pod 'HDDynamicPod', :path => '../../../HDDynamicPod/HDDynamicPod'

  target 'HDStaticPod_Tests' do
    inherit! :search_paths
  end
end
